github: [metadata]

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robin Percy
email: robin@percy.pw
description: >- # this means to ignore newlines until "baseurl:"
  One of the longest serving and most experienced Developer Evangelists in Europe, an avid Technical Writer, a Polyglot Programmer and worker of all-things Developer Relations.  Twice Startup CEO & CTO.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://robin.percy.pw" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rbin
github_username:  rbnpercy

show_excerpts: true
permalink: /:year/:month/:title
header_pages:
  - about.md
  - other-articles.md
  - ping-me.md

google_analytics: UA-118207320-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
